const user = {
    'SET_USER_SIGN_UP_FORM': 'user/SET_USER_SIGN_UP_FORM',
    'SET_USER_GENDER': 'user/SET_USER_GENDER',
    'SET_USER_NAME': 'user/SET_USER_NAME',
    'SET_USER_SPOUSE_NAME': 'user/SET_USER_SPOUSE_NAME',
    'SET_USER_MARRIAGE_DATE': 'user/SET_USER_MARRIAGE_DATE',
    'SET_USER_PREP_COST': 'user/SET_USER_PREP_COST',
    'SET_IS_USER_AUTH_FORM': 'user/SET_IS_USER_AUTH_FORM'
}

const checklist = {
    'SET_CHECKLIST_DATA': 'checklist/SET_CHECKLIST_DATA',
    // 'SET_COMPLETED_FOR_A_TASK': 'checklist/SET_COMPLETED_FOR_A_TASK',
    'SET_SELECTED_TASK': 'checklist/SET_SELECTED_TASK',
    'SET_OPEN_TASK_FORM': 'checklist/SET_OPEN_TASK_FORM',
    'RESET_SELECTED_TASK': 'checklist/RESET_SELECTED_TASK',
    'SET_TOAST_DATA': 'checklist/SET_TOAST_DATA'
}

export default {
    user,
    checklist
}