const AUTHENTICATED = 'AUTHENTICATED'
const PARTIAL_AUTHENTICATED = 'PARTIAL_AUTHENTICATED'
const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'

export {
    AUTHENTICATED,
    PARTIAL_AUTHENTICATED,
    NOT_AUTHENTICATED
}